### ISSUE TITLE
small roadmap 

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/full-app#19]
## Main scenario  

What is this apllication is for:
- [ ] read data from parsers
- [x] store data in one table in database
- [ ] make the query to read by name, freq and start/end date limits

А. To achive this in Django we need:
- django functionality provided by @tinivir 
- django implementation understood by @epogrebnyak and @zarak 
- data provided by @epogrebnyak 

B. To do this we well we need:
- testing of main scenario
- refining django infrastucture

After A+B is achived we deploy to heroku/postgres.

**Comment by epogrebnyak** [comment]
In main scenario we do not have (documented) functionality:
- import from the parsers - #9 
- make the query - #8 

Labelled as <https://github.com/mini-kep/full-app/labels/main_scenario>. 

@tinivir - this we have to talk through in issues - what is implemented and how to use it.

**Comment by epogrebnyak** [comment]
In testing we have following tasks:
- [x] ensure existing methods for #8 are covered by test 
- [ ] ensure methods for #9 are covered by test 
- [x] small task on bagde closes #16 probably closes #3 @tinivir

**Comment by epogrebnyak** [comment]
@tinvir - please decouple the settings for various cases in #13

**Comment by epogrebnyak** [comment]
I need to produce the sample dataset and review CRUD tests:
- [ ] #18 
- [ ] #10 
- [ ] #7
